export enum Category {
  IMMOBILIER = 'IMMOBILIER',
  AUTOMOBILE = 'AUTOMOBILE',
  EMPLOI = 'EMPLOI',
  SERVICES = 'SERVICES',
  LOISIRS = 'LOISIRS',
  REAL_ESTATE = "REAL_ESTATE",
  VEHICLE = "VEHICLE",
  JOB = "JOB",
  MISC = "MISC",
  ELECTRONICS = "ELECTRONICS",
  FASHION = "FASHION"
}
